config/routes.rb
Rails.application.routes.draw do

  resources :projects

  resources :tasks

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  validates :name, presence: true,
            length: { minimum: 5 }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    @tasks = Task.all
  end

  def new
    @project = Project.new
  end

  def create
    @projects = Project.all
    @project = Project.new(project_params)
    @project.save
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @projects = Project.all
    @project = Project.find(params[:id])

    @project.update_attributes(project_params)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @tasks = Task.all
    @task = Task.new(task_params)
    @task.save
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @tasks = Task.all
    @task = Task.find(params[:id])

    @task.update_attributes(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to projects_path
  end

  private
  def task_params
    params.require(:task).permit(:name, :project_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PsProjectManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_backup/edit.html.erb
<%= link_to 'Back', projects_path %>

<%= form_for :project, url: project_path(@project), method: :patch do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :actual %><br>
      <%= f.text_field :actual %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/projects/_backup/index.html.erb
<h3>Index</h3>

<%= link_to 'New project', new_project_path %>

<% @projects.each do |project| %>
  <div class="project">
    <%= project.name %>
    Project id: <%= project.id %>
    <%= link_to 'Edit', edit_project_path(project) %>
    <%=
      link_to 'Destroy',
      project_path(project),method: :delete,
      data: { confirm: 'Are you sure?' }
    %>
    <ul>
      <% @tasks.each do |task| %>
          <%if(project.id == task.project_id)%>
            <li>
              <%= task.name %>
              <%= task.description %>
              Project id: <%= task.project_id %>
            </li>
          <%end%>
      <% end %>
    </ul>

  </div>
<% end %>

app/views/projects/_backup/new.html.erb
<%= link_to 'Back', projects_path %>

<%= form_for :project, url: projects_path do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/projects/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@project.name}" %></h3>
</div>
<%= render 'form' %>

app/views/projects/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @project, remote: true do |f| %>
        <div class="modal-body">
          <ul class="errors"></ul>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit %>
          <%= link_to 'Cancel', '#', class: '#', data: {dismiss: 'modal'} %>
        </div>
    <% end %>
  </div>
</div>

app/views/projects/_index.html.erb
<% @projects.each do |project| %>

    <div>
      <div class="ps-header">
        <%= project.name %>
        <%= link_to 'Edit', edit_project_path(project), remote: true %>
        <%= link_to 'Destroy', project_path(project), method: :delete %>
      </div>
    </div>

    <ul>
      <% @tasks.each do |task| %>
          <li>
            <%= form_for @task, remote: true do |f| %>
              <%= f.label :name %>
              <%= f.text_field :name %>
              <%= f.submit %>
            <% end %>
          </li>
          <li>
            <%= task.name %>
            <%= task.description %>
            Project id: <%= task.project_id %>
            <%= link_to 'Edit', edit_task_path(task), remote: true %>
            <%= link_to 'Destroy', task_path(task), method: :delete %>
          </li>
      <% end %>
    </ul>

<% end %>

app/views/projects/_new.html.erb
<div class="modal-header">
  <h3>New Project</h3>
</div>
<%= render 'form' %>

app/views/projects/_save.js.erb
$(".project-index").html("<%= escape_javascript(render 'index') %>");
$("#project-modal").modal("hide");

app/views/projects/create.js.erb
<%= render 'save' %>

app/views/projects/edit.js.erb
$("#project-modal").html("<%= escape_javascript(render 'edit') %>");
$("#project-modal").modal("show");

app/views/projects/index.html.erb
<div class="container">
  <%= link_to 'New project', new_project_path, remote: true, class: 'btn btn-primary' %>
  <div class="new-project"></div>
  <%= render 'index' %>
</div>

<div id="project-modal" class="modal fade"></div>

app/views/projects/new.js.erb
$("#project-modal").html("<%= escape_javascript(render 'new') %>");
$("#project-modal").modal("show");

app/views/projects/update.js.erb
<%= render 'save' %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>